test_app/config/routes.rb
TestApp::Application.routes.draw do
  resources :users

  root to: 'root#index'

end

test_app/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :date_of_birth, :description
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

test_app/app/controllers/root_controller.rb
class RootController < ApplicationController

  def index
    if User.first
      redirect_to User.first
    else
      redirect_to controller: 'users', action: 'index'
    end
  end

end

test_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to @user, :notice => "Successfully created user."
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      respond_to do |format|
        format.json { respond_with_bip( @user ) }
        format.html { redirect_to @user, :notice  => "Successfully updated user." }
      end
    else
      render :action => 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_url, :notice => "Successfully destroyed user."
  end
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
end

test_app/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

test_app/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

test_app/app/helpers/markdown_helper.rb
module MarkdownHelper
  # This method returns the given markdown code rendered as html.
  # Have a look at these sources:
  #   * http://railscasts.com/episodes/272-markdown-with-redcarpet
  #   * https://github.com/vmg/redcarpet
  #   * http://daringfireball.net/projects/markdown/syntax
  #
  def markdown(text, options = nil)
    options ||= { hard_wrap: true, filter_html: true, autolink: true, no_intraemphasis: true, fenced_code: true, gh_blockcode: true }
    Redcarpet::Markdown.new(Redcarpet::Render::HTML, options).render(sanitize(text) || "").html_safe
  end
end

# In order to use the markdown helper method with best_in_place's :display_with argument, 
# the ActionView::Base has to include the markdown method.
#
module ActionView
  class Base
    include MarkdownHelper
  end
end

test_app/app/helpers/users_helper.rb
module UsersHelper
end

test_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

test_app/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </p>
  <p>
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </p>
  <p>
    <%= f.label :date_of_birth %><br />
    <%= f.date_select :date_of_birth %>
  </p>
  <p><%= f.submit %></p>
<% end %>

test_app/app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @user %> |
  <%= link_to "View All", users_path %>
</p>

test_app/app/views/users/index.html.erb
<% title "Users" %>

<p>
  This demo app shows how <a href="https://github.com/fiedl/edit_mode" target="_blank">edit_mode</a> looks like.
</p>
<p>
  Just go to the 'show' page of a user and edit his profile there. (If no user exists, you will have to create one first.)
</p>


<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Date Of Birth</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.date_of_birth %></td>
      <td><%= link_to "Show", user %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

test_app/app/views/users/new.html.erb
<% title "New User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", users_path %></p>

test_app/app/views/users/show.html.erb
<% title "User: " + @user.first_name + " " + @user.last_name %>


<p>
  This <strong>edit mode demo app</strong> shows how <a href="https://github.com/fiedl/edit_mode" target="_blank">edit_mode</a> looks like.
</p>
<p>
  You can either click on the information to directly edit them via <a href="https://github.com/bernat/best_in_place" target="_blank">best_in_place</a>, or you can use the 'edit' links to activate the edit mode.
</p>

<div class="edit_mode_group">
  <span class="edit_mode_tools">
    <a class="edit_button" href="#">edit</a>
    <a class="cancel_button" href="#">cancel</a>
    <a class="save_button" href="#">save</a>
  </span>

  <h2>Basic Information</h2>
  <p>
    <strong>First Name:</strong>
    <%= best_in_place @user, :first_name %>
  </p>
  <p>
    <strong>Last Name:</strong>
    <%= best_in_place @user, :last_name %>
  </p>
</div>

<div class="edit_mode_group">
  <span class="edit_mode_tools">
    <a class="edit_button" href="#">edit</a>
    <a class="cancel_button" href="#">cancel</a>
    <a class="save_button" href="#">save</a>
  </span>

  <h2>Markdown Description</h2>
  <%= best_in_place @user, :description, display_with: :markdown, type: :textarea %>
</div>

<div class="edit_mode_group">
  <span class="edit_mode_tools">
    <a class="edit_button" href="#">edit</a>
    <a class="cancel_button" href="#">cancel</a>
    <a class="save_button" href="#">save</a>
  </span>

  <h2>Additional Information</h2>
  <p>
    <strong>Date Of Birth:</strong>
    <%= best_in_place @user, :date_of_birth %>
    <span class="show_only_in_edit_mode"><a href="#" title="this link does not do anything in this demo.">delete</a></span>
  </p>
  <span class="show_only_in_edit_mode">
    <a href="#" title="this link does not do anything in this demo.">add</a>
  </span>
</div>

<p class="global_tools">
  <!--
    <%= link_to "Edit", edit_user_path(@user) %> |
    <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  -->
  <%= link_to "View All Users", users_path %>
</p>